### ISSUE TITLE
500 Error when Trying to Verify Slack App

### ISSUE THREAD

**Issue by hops-on-pop** [uhavin/slackers#18]
We're trying to incorporate this library into an FAQ API we've built on top of FastAPI. 

When we try to enable the endpoint via Slack, the response is an HTTP error. 

Here is the output from uvicorn:
```
INFO:     44.195.79.65:52938 - "POST /slack/events HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 191, in app
    solved_result = await solve_dependencies(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/dependencies/utils.py", line 548, in solve_dependencies
    solved = await call(**sub_values)
  File "/usr/local/lib/python3.8/dist-packages/slackers/verification.py", line 29, in verify_signature
    os.environ.get("SLACK_SIGNING_SECRET").encode(), to_verify, sha256
AttributeError: 'NoneType' object has no attribute 'encode'
```

The routes appear on the FastAPI /docs page (screenshot attached) 
![FastAPI_routes](https://user-images.githubusercontent.com/13441375/131584238-f1d7120f-2e0e-4dad-abb5-741696c210f8.jpg)

For now, we've just included the very basics of the code implementation, which we understand should automatically handle the Slack Events requests. We've also confirmed that the env variables are set on the OS (Ubuntu). 

```

from fastapi import FastAPI, HTTPException
import uvicorn

# SlackBot Imports
import os
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from slackers.server import router
from slackers.hooks import actions
from slackers.hooks import responder
from slackers.hooks import events
from dotenv import load_dotenv

# Slack variables
load_dotenv()
signing_secret = os.environ.get("SLACK_SIGNING_SECRET")
slack_token = os.environ.get("SLACK_BOT_TOKEN")

app = FastAPI()
app.include_router(router, prefix='/slack')
```

Any help is greatly appreciated and please let me know if you need more info.

**Comment by uhavin** [comment]
@hops-on-pop I realize I am a bit late in answering you. Are you still encountering this issue? It's really hard to tell why this is happening as it seems to be specific to your machine. The error message implies your environment is not set correctly but you asserted you set it. 

If you print your variable `slack_signing_secret`, does it hold your value? And what happens if you put `os.environ["SLACK_SIGNING_SECRET"] = "gibberish"` somewhere between `load_dotenv` and `app = FastAPI()`, does it still raise the same error or do you get a 403 instead?

**Comment by hops-on-pop** [comment]
@uhavin - Thanks for following up!

It turned out we had an issue with the ENV Variables being cleared when we started a particular application process.  We were able to resolve the issue and successfully validate the Slack App.
